//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokedex_definitivo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PokedexEntities : DbContext
    {
        public PokedexEntities()
            : base("name=PokedexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Captura> Capturas { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Debilidad> Debilidads { get; set; }
        public virtual DbSet<Entrenador> Entrenadors { get; set; }
        public virtual DbSet<Entrenador_medallas> Entrenador_medallas { get; set; }
        public virtual DbSet<Evolucione> Evoluciones { get; set; }
        public virtual DbSet<Habilidade> Habilidades { get; set; }
        public virtual DbSet<Medalla> Medallas { get; set; }
        public virtual DbSet<Pokemon> Pokemons { get; set; }
        public virtual DbSet<Tipo> Tipoes { get; set; }
    }
}
