//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokedex_definitivo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debilidad
    {
        public int de_id { get; set; }
        public int id_tipo1 { get; set; }
        public int id_tipo2 { get; set; }
    }
}
